[global]
# Configuration globale Streamlit
developmentMode = false
showWarningOnDirectExecution = false

[server]
# Configuration serveur pour déploiement
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false

[browser]
# Configuration navigateur
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
# Thème personnalisé PhytoAI
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
# Configuration client
showErrorDetails = false
toolbarMode = "viewer"

[ui]
# Interface utilisateur
hideTopBar = false
hideSidebarNav = false 